[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "dCtCTU1CYTY0QWpCU3puTUttMEM0WWpIUlJtWXNpdnBRRWtDeEtVbmpzUT0="
client_id =  "670470598976-7becscoth3i5kd1pd4jhvqobt35ja1q0.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"