[auth]
client_id = "670470598976-7becscoth3i5kd1pd4jhvqobt35ja1q0.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://myet-v3-dev.streamlit.app/oauth2callback"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
cookie_secret = "dCtCTU1CYTY0QWpCU3puTUttMEM0WWpIUlJtWXNpdnBRRWtDeEtVbmpzUT0="