REDIRECT_URI="http://localhost:8501/oauth2callback"
COOKIE_SECRET="9as8dasdhasjdjlaskdhasdghgsad"
CLIENT_ID="670470598976-ah0n0ioh0ilbhpesdtbmg6omgldmu4j8.apps.googleusercontent.com"
CLIENT_SECRET=<Auth0 client secret>
AUTH0_METADATA_URL=https://<tenant>.auth0.com/.well-known/openid-configuration
